### ISSUE TITLE
Ghost Style not working as expected.

### ISSUE THREAD

**Issue by biologyscience** [mfuu/sortable-dnd#2]
### Code:
```html
<!-- inside body -->
<ul id="group">
    <li>
        <p>1</p>
    </li>
    <li>
        <p>2</p>
    </li>
    <li>
            p>3</p>
    </li>
    <li>
        <p>4</p>
    </li>
    <li>
        <p>5</p>
    </li>
    <li>
        <p>6</p>
    </li>
</ul>
```
```css
/* CSS */
body
{
    background-color: grey;
}

ul
{
    list-style: none;
}
            
li
{
    width: 100px;
    color: white;
    background-color: purple;
    padding: 0 .5em;
}
```
```js
// JS
const Sortable = require('sortable-dnd');

new Sortable(
    document.getElementById('group'),
    {
        ghostStyle:
        {
            display: 'none'
        }
    }
);
```
---
(I'm using this code in a Node environment)

So, basically I want to hide the ghost element completely using the style `display: none;` property, like [this](https://biologyscience.github.io/tempShare/drag).  
But unfortunately it looks something like [this](https://cdn.discordapp.com/attachments/755414148183228506/1006203087658160249/unknown.png).

Is there any possible solution for this ?
